#!/usr/bin/env python3
"""Generate RESULTS.md from DuckDB benchmark corpus.

Usage:
    uv run scripts/bench_report.py [--db bench/x_uma_bench.duckdb] [--output bench/RESULTS.md]

Queries the latest benchmark run and generates a narrated comparison report.
"""

from __future__ import annotations

import sys
from pathlib import Path

import click
import duckdb


DB_DEFAULT = "bench/x_uma_bench.duckdb"
OUTPUT_DEFAULT = "bench/RESULTS.md"


def fmt_ns(ns: float) -> str:
    """Format nanoseconds into human-readable string."""
    if ns < 1_000:
        return f"{ns:.0f}ns"
    if ns < 1_000_000:
        return f"{ns / 1_000:.1f}us"
    if ns < 1_000_000_000:
        return f"{ns / 1_000_000:.1f}ms"
    return f"{ns / 1_000_000_000:.2f}s"


def fmt_speedup(slow: float, fast: float) -> str:
    """Format speedup ratio."""
    if fast <= 0:
        return "N/A"
    ratio = slow / fast
    return f"{ratio:.1f}x"


@click.command()
@click.option("--db", default=DB_DEFAULT, help="DuckDB database path")
@click.option("--output", default=OUTPUT_DEFAULT, help="Output markdown file")
def main(db: str, output: str) -> None:
    """Generate benchmark report from DuckDB."""
    if not Path(db).exists():
        click.echo(f"Database {db} not found. Run `just bench-ingest` first.", err=True)
        sys.exit(1)

    con = duckdb.connect(db, read_only=True)

    # Get latest run
    run = con.execute(
        "SELECT id, commit_sha, timestamp, machine, notes FROM bench_runs ORDER BY id DESC LIMIT 1"
    ).fetchone()

    if not run:
        click.echo("No benchmark runs found.", err=True)
        sys.exit(1)

    run_id, commit_sha, timestamp, machine, notes = run

    # Get all results for this run
    results = con.execute(
        """SELECT variant, scenario, phase, mean_ns, stddev_ns, min_ns, max_ns, iterations
           FROM bench_results
           WHERE run_id = ?
           ORDER BY scenario, phase, mean_ns""",
        [run_id],
    ).fetchall()

    if not results:
        click.echo(f"No results for run #{run_id}.", err=True)
        sys.exit(1)

    # Build report
    lines: list[str] = []
    lines.append("# x.uma Benchmark Results\n")
    lines.append(f"**Run #{run_id}** | Commit: `{commit_sha}` | {timestamp}")
    lines.append(f"Machine: {machine}")
    if notes:
        lines.append(f"Notes: {notes}")
    lines.append("")

    # Cross-variant comparison table
    lines.append("## Cross-Variant Comparison\n")

    # Group by scenario + phase
    scenarios: dict[tuple[str, str], list[tuple]] = {}
    for row in results:
        key = (row[1], row[2])  # scenario, phase
        scenarios.setdefault(key, []).append(row)

    for (scenario, phase), rows in sorted(scenarios.items()):
        lines.append(f"### {scenario} ({phase})\n")
        lines.append("| Variant | Mean | Stddev | Min | Max | Iterations |")
        lines.append("|---------|------|--------|-----|-----|------------|")

        for row in rows:
            variant, _, _, mean, stddev, min_ns, max_ns, iters = row
            lines.append(
                f"| {variant} | {fmt_ns(mean)} | {fmt_ns(stddev or 0)} "
                f"| {fmt_ns(min_ns or 0)} | {fmt_ns(max_ns or 0)} "
                f"| {iters or 'N/A'} |"
            )
        lines.append("")

    # FFI overhead analysis
    lines.append("## FFI Overhead Analysis\n")

    ffi_pairs = [("puma", "puma-crusty"), ("bumi", "bumi-crusty")]
    for pure, crusty in ffi_pairs:
        ffi_results = con.execute(
            """SELECT
                pure.scenario, pure.phase,
                pure.mean_ns AS pure_ns,
                crusty.mean_ns AS crusty_ns
            FROM bench_results pure
            JOIN bench_results crusty
              ON pure.scenario = crusty.scenario
             AND pure.phase = crusty.phase
             AND pure.run_id = crusty.run_id
            WHERE pure.variant = ? AND crusty.variant = ?
              AND pure.run_id = ?
            ORDER BY pure.scenario, pure.phase""",
            [pure, crusty, run_id],
        ).fetchall()

        if ffi_results:
            lines.append(f"### {pure} vs {crusty}\n")
            lines.append("| Scenario | Phase | Pure | Crusty | Speedup |")
            lines.append("|----------|-------|------|--------|---------|")
            for scenario, phase, pure_ns, crusty_ns in ffi_results:
                lines.append(
                    f"| {scenario} | {phase} | {fmt_ns(pure_ns)} "
                    f"| {fmt_ns(crusty_ns)} | {fmt_speedup(pure_ns, crusty_ns)} |"
                )
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by `scripts/bench_report.py` from DuckDB benchmark corpus.*")
    lines.append("")

    con.close()

    report = "\n".join(lines)
    Path(output).write_text(report)
    click.echo(f"Report written to {output} ({len(results)} results)")


if __name__ == "__main__":
    main()
